"""Questions Model

Revision ID: 33c055757140
Revises: d321eecb6fc2
Create Date: 2024-12-07 16:23:31.343092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c055757140'
down_revision = 'd321eecb6fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.String(length=64), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('options', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_quiz_id'), ['quiz_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_quiz_id'))

    op.drop_table('question')
    # ### end Alembic commands ###
