"""adding score to user_quizzes

Revision ID: 40afaa0fe17c
Revises: ac3ec969732a
Create Date: 2025-01-05 21:40:05.953167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40afaa0fe17c'
down_revision = 'ac3ec969732a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quizzes', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
