"""quiz state column

Revision ID: 74038abaf112
Revises: 5584bbaad666
Create Date: 2024-12-23 20:16:46.264465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74038abaf112'
down_revision = '5584bbaad666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
