"""current question

Revision ID: 7f52a41d0f9c
Revises: c924f51a2bbe
Create Date: 2024-12-13 07:18:05.391225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f52a41d0f9c'
down_revision = 'c924f51a2bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_question_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_quiz_current_question_id_question', 'question', ['current_question_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_question_id')

    # ### end Alembic commands ###
