"""updated relationships to reference the user not the player

Revision ID: ac3ec969732a
Revises: 1809465b3b35
Create Date: 2025-01-05 18:59:19.886046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3ec969732a'
down_revision = '1809465b3b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_quizzes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'quiz_id', name='pk_user_quizzes')

    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_answer_player_id')
        batch_op.create_index(batch_op.f('ix_answer_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_answer_user_id_user', 'user', ['user_id'], ['id'])  # Added constraint name
        batch_op.drop_column('player_id')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'player', ['player_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_answer_user_id'))
        batch_op.create_index('ix_answer_player_id', ['player_id'], unique=False)
        batch_op.drop_column('user_id')

    op.drop_table('user_quizzes')
    # ### end Alembic commands ###
