"""current question table

Revision ID: b0097570da66
Revises: 7f52a41d0f9c
Create Date: 2024-12-21 05:42:19.817167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0097570da66'
down_revision = '7f52a41d0f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.String(length=64), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_id')
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_current_question_id_question', type_='foreignkey')
        batch_op.drop_column('current_question_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_question_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_quiz_current_question_id_question', 'question', ['current_question_id'], ['id'])

    op.drop_table('current_question')
    # ### end Alembic commands ###
