"""add number of players to quiz model

Revision ID: e1b0dfedb9df
Revises: 2fa56b371687
Create Date: 2024-12-08 08:57:47.744420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b0dfedb9df'
down_revision = '2fa56b371687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_players', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('num_players')

    # ### end Alembic commands ###
